(define (crayon-fx-pastel pattern)
  (let* ((filelist (cadr (file-glob pattern 1))))
  (define crayon1 (string-append gimp-directory "/scripts/image/crayontex01.png"))
  (define crayon2 (string-append gimp-directory "/scripts/image/crayontex02.png"))
  (define texture crayon1)
    (while (not (null? filelist))
           (let* ((filename (car filelist))
                  (image (car (gimp-file-load RUN-NONINTERACTIVE
                                              filename filename)))
                  (drawable (car (gimp-image-get-active-layer image))))
                  
             (gimp-image-add-layer image (car (gimp-file-load-layer RUN-NONINTERACTIVE image texture)) 10)
             (gimp-layer-set-mode (vector-ref (car (cdr (gimp-image-get-layers image))) 0) DODGE-MODE)
             (gimp-image-flatten image)
             (set! drawable (car (gimp-image-get-active-layer image)))
             (gimp-brightness-contrast drawable -20 60)
             (gimp-file-save RUN-NONINTERACTIVE image drawable filename filename)
             (gimp-image-delete image))
             (if (string=? texture crayon1)
                (set! texture crayon2)
                (set! texture crayon1))
           (set! filelist (cdr filelist)))))
